# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ddbbfe2b9bfe44a9b5ce027df6b7fb381994a8c1e490ce50e981446381b4de3a0e747326b07754f572b0c4cba75bd0544417d57eac692707a9fd995ea25b8320

test:
  secret_key_base: c042c056183d1a6debcdefe8965359eb88ce1f870667834f8861077b348d4fd6dcdca0a267c9eee008db03c41185fee6ba11d8cb081e75197c02518b15c12a8e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
